### PR TITLE
moved the test config to manifests folder

### PR DESCRIPTION
**Pull request by shubhamdixit863**
Yes

Fixes https://github.com/numaproj-labs/numaplane/issues/101

### Modifications
Modified the config.yaml file  in tests/manifests folder with the latest fields
Modified config tests and the controller tests to use the config file from tests/manifests folder

### Verification

As no new feature has been added ,only the existing tests cases have been checked if they run properly

### CODE REVIEW

**Comment by juliev0** [comment]
Sorry, I think this Issue maybe wasn't clear. I was specifically hoping our tests could no longer reference repos like:
- https://github.com/numaproj-labs/numaplane-control-manifests
- https://github.com/numaproj/numaflow
And we could just put all of the files that we need for these tests within this repo instead, in `tests/manifests`.

**Comment by shubhamdixit863** [comment]
> Sorry, I think this Issue maybe wasn't clear. I was specifically hoping our tests could no longer reference repos like:
> 
> - https://github.com/numaproj-labs/numaplane-control-manifests
> 
> - https://github.com/numaproj/numaflow
> 
> And we could just put all of the files that we need for these tests within this repo instead, in `tests/manifests`.

ok i will modify that .

**Comment by shubhamdixit863** [comment]
@juliev0 i have checked we are not using any resources  as of now from these git urls ,we are just using these urls for performing gitsync  tests in util_test.go . So I believe we dont have any dependency on these external repos

**Comment by juliev0** [comment]
> @juliev0 i have checked we are not using any resources as of now from these git urls ,we are just using these urls for performing gitsync tests in util_test.go . So I believe we dont have any dependency on these external repos

This is an example of a dependency on the numaflow repo: https://github.com/numaproj-labs/numaplane/blob/main/internal/git/util_test.go#L279 Let's say that `config/namespace-install` directory changes...

**Comment by shubhamdixit863** [comment]
No longer needed

**Pull request closed without merging**
