### PR TITLE
Fix the cloned repo update issue

### LINKED ISSUE #218: Repo sync is not working for Kustomize and Helm
**Describe the bug**

**To Reproduce**

1. Apply gitsync for Kustomize repo
2. Delete any resource from Kustomize repo

**Expected behavior**

- Any resource deleted from Kustomize repo should be deleted from cluster too

**Screenshots**
- After any change in repo and synced via numaplane the local repo should not show `Changes to be committed` in as below

Screenshot 2024-04-18 at 12 19 29 PM

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by chandankumar4**
Fixes #218 

### Modifications

- After sync the repo status looks fine also it's able to delete/create any resource accordingly 

Screenshot 2024-04-18 at 12 23 49 PM

### Verification

Verified in local k8s cluster using below gitsync
```bash
apiVersion: numaplane.numaproj.io/v1alpha1
kind: GitSync
metadata:
  name: gitsync-example
  namespace: numaplane-system
spec:
  path: "kustomize-example/cluster-install"
  repoUrl: https://github.com/chandankumar4/numaplane-sample.git
  targetRevision: main
  kustomize: {}
  destination:
    cluster: staging-usw2-k8s
    namespace: numaflow-pipeline
```

### CODE REVIEW

**Review by dpadhiar — COMMENTED** [review]
LGTM - should fix issue with Kustomize manifests I was seeing

**Comment by chandankumar4** [comment]
Had tested with Helm as well and syncing is working fine.

**Comment by xdevxy** [comment]
> Had tested with Helm as well and syncing is working fine.

@chandankumar4 have you test if remote repo change will also work? https://github.com/chandankumar4/numaplane-sample/tree/main/kustomize-remote-example? Thanks a lot!

**Review by xdevxy — COMMENTED** [review]
what is the root cause here? is it because not able to pull from the local repo or it is not able to commit to the local repo? And this is not related to kustomize and helm syncing features right?

**Review by xdevxy — APPROVED** [review]

**Comment by juliev0** [comment]
feel free to merge @xdevxy

**Comment by chandankumar4** [comment]
> what is the root cause here? is it because not able to pull from the local repo or it is not able to commit to the local repo? And this is not related to kustomize and helm syncing features right?

It was not able to commit to local repo, yes it was not related to kustomize and helm syncing feature

**Comment by chandankumar4** [comment]
> > Had tested with Helm as well and syncing is working fine.
> 
> @chandankumar4 have you test if remote repo change will also work? https://github.com/chandankumar4/numaplane-sample/tree/main/kustomize-remote-example? Thanks a lot!

Yes, remote sync will work as it is as it not an issue with kustomize or helm, it was issue with repo sync issue, as fetch was not able to commit changes to local branch

**Pull request merged**
